There was an error executing ["sudo", "/usr/local/bin/vagrant-lxc-wrapper", "ifconfig", "vlxcbr0", "up"]

diff --git a/scripts/pipework b/scripts/pipework
--- a/scripts/pipework
+++ b/scripts/pipework
@@ -188,8 +188,11 @@ if [ $DOCKERPID ]; then
 else
   NSPID=$(head -n 1 $(find "$CGROUPMNT" -name "$GUESTNAME" | head -n 1)/tasks)
   [ "$NSPID" ] || {
-      echo "Could not find a process inside container $GUESTNAME."
-      exit 1
+    # it is an alternative way to get the pid
+    NSPID=$(lxc-info -n  "$GUESTNAME" | grep PID | grep -Eo '[0-9]+')
+    [ "$NSPID" ] || {
+      die 1 "Could not find a process inside container $GUESTNAME."
+    }
   }
 fi
 
